apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components: []

labels:
- includeSelectors: true
  pairs:
    copy-from-bootstrap-to-management: ""

configMapGenerator:
- name: sylva-units-values
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - values=values.yaml

secretGenerator:
- name: sylva-units-secrets
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
  - secrets=secrets.yaml
